spring.application.name=payment-service
server.port=8083

# Database Configuration (Updated to use the shared database)
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce-db?options=-c%20timezone=UTC
spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=payment-group
spring.kafka.consumer.auto-offset-reset=earliest